# Day 1: Python + NumPy Basics
Welcome to Day 1. Today I'll revise core Python essentials and start working with NumPy arrays.

Let's keep the basics short.

## Python Data Types and Variables
Revision starts with- integers, floats, strings, booleans and lists.

In [ ]:
a = 5                           #integer
b = 5.5                         #float
c = "Prashant Gliv"             #string
d = True                        #boolean
e = [1,2,3,4,5]                 #list

print(type(a),type(b),type(c),type(d),type(e))

We understood the data types. Now, let's focus on NumPy.

## Getting familiar with NumPy

First, install the library.

In [ ]:
!pip install numpy

Once installed, import it using the code below.

In [3]:
import numpy as np

## NumPy Arrays
Let's create our first numpy array.

In [4]:
arr= np.array([10,20,30,40,50])
print("Array: ", arr)
print("Shape: ", arr.shape)
print("Data Type: ", arr.dtype)

Array:  [10 20 30 40 50]
Shape:  (5,)
Data Type:  int64


## Array Dimensions
Reviewing array dimensions now-

In [12]:

#0-D array
a=np.array(32)
print("O-D: ",a ,"Shape: ",a.shape)

#1-D array
b=np.array([10,20,30])
print("1-D: ",b,"Shape: ",b.shape)

#2-D array
c= np.array([[1,2],[3,4]])
print("2-D: ",c ,"Shape: ",c.shape)

#3-D array
d= np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print("3-D: ",d ,"Shape: ",d.shape)


O-D:  32 Shape:  ()
1-D:  [10 20 30] Shape:  (3,)
2-D:  [[1 2]
 [3 4]] Shape:  (2, 2)
3-D:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] Shape:  (2, 2, 2)


## Array Indexing & Slicing 
Doesn't differ much from lists in python- just more dimensions.

Basic Indexing-

In [8]:
arr = np.array([10,20,30,40,50])
print( arr[0])
print(arr[-1])

10
50


Slicing-

In [9]:
print(arr[1:3])

[20 30]


2-D Indexing-

In [10]:
arr2d= np.array([[1,2,3], [4,5,6]])
print(arr2d[0,1])           #row 0, column 1
print(arr2d[:,1])           #all rows, column 1

2
[2 5]


## Practice 1.0

In [11]:
arr= np.array([[10,20,30],
               [40,50,60],
               [70,80,90]])
print("Element at row 1 and column 2: ", arr[1,2])
print("Full first row: ", arr[0])
print("Full last column: ", arr[:, -1])
print("Middle 2x2 block: ", arr[0:2, 1:3])

Element at row 1 and column 2:  60
Full first row:  [10 20 30]
Full last column:  [30 60 90]
Middle 2x2 block:  [[20 30]
 [50 60]]


## Broadcasting
This is how NumPy handles operations between arrays of different shapes. 

In [14]:
a = np.array([1,2,3])
b= np.array([4,5,6])

#Element-wise operations
print("a + b is: ", a+b)
print("a * b is: ", a*b)

#Scalar operation
print("a * 2 is: ", a*2)

#Broadcasting (adding 1D to 2D)
c= np.array([[10,20,30],[40,50,60]])
print("Broadcasted Addition:\n", b+c)

#useful functions
print("Sum: ", np.sum(c))
print("Mean of each column: ", np.mean(c, axis= 0 ))
print("Max in each row: ", np.max(c, axis=1))

a + b is:  [5 7 9]
a * b is:  [ 4 10 18]
a * 2 is:  [2 4 6]
Broadcasted Addition:
 [[14 25 36]
 [44 55 66]]
Sum:  210
Mean of each column:  [25. 35. 45.]
Max in each row:  [30 60]


## Practice 2.0

In [ ]:
arr= np.array([[10,20],[30,40],[50,60]])
print("Original array: \n")

print("Shape: ", arr.shape)
print("Multiply every element by 3: ", arr*3)

#add [1,2] to every row (broadcasting)
print("Broadcasting: \n", arr + np.array([1,2]))

#find sum of each row
print("Sum of each row: ", np.sum(arr, axis=1))

Original array: 

Shape:  (3, 2)
Multiply every element by 3:  [[ 30  60]
 [ 90 120]
 [150 180]]
Broadcastion: 
 [[11 22]
 [31 42]
 [51 62]]
Sum of each row:  [ 30  70 110]


## Day 1 FINISHED.